basePath: /
definitions:
  models.Class:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  models.CreateClassRequest:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - name
    type: object
host: localhost:8082
info:
  contact: {}
  description: This is the Class Service API
  title: Class Microservice API
  version: "1.0"
paths:
  /classes:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all classes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Class'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Get all classes
      tags:
      - class
    post:
      consumes:
      - application/json
      description: Create a new class with name and description
      parameters:
      - description: Create Class Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.CreateClassRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - BearerAuth: []
      summary: Create a new class
      tags:
      - class
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
